### ISSUE TITLE
求大佬带带我

### ISSUE THREAD

**Issue by kakaxi-1** [kenziao2022/mytv#1]
纯小白，今天注册的，硬是不会玩。以前是直接薅羊毛复制粘贴到电视tivimate上就能看，现在是找不到复制粘贴的，都是在项目里面一个文件，完全不会弄了，求带。另外自己做的话，源是在哪里找，是需要自己每天更新吗？再就是节目预告信息，也是需要每天更新吗？

**Comment by kenziao2022** [comment]
我也是小白，只会做最低端的找源存到GITHUB，再把地址复制到TVBOX用。节目预告一窍不通。我用的是酒店源，人工复制粘贴。什么时候时效什么时候替换，最原始的办法

**Comment by kakaxi-1** [comment]
> 我也是小白，只会做最低端的找源存到GITHUB，再把地址复制到TVBOX用。节目预告一窍不通。我用的是酒店源，人工复制粘贴。什么时候时效什么时候替换，最原始的办法

那也是大佬，我完全不会，找源也不会，都是用的网上的

**Comment by kenziao2022** [comment]
> > 我也是小白，只会做最低端的找源存到GITHUB，再把地址复制到TVBOX用。节目预告一窍不通。我用的是酒店源，人工复制粘贴。什么时候时效什么时候替换，最原始的办法
> 
> 那也是大佬，我完全不会，找源也不会，都是用的网上的

http://tonkiang.us/ 用这个搜酒店源。这些源基本上三五天就失效了，需要及时检查替换。

**Comment by kenziao2022** [comment]
你是天津联通的话可以直接用我的。如果不是，就只能自己找了
